service: paramiko-py37

provider:
  name: aws
  profile: jb

layers:
  paramiko:
    path: build
    name: paramiko-py37
    description: Provides Paramiko SSH library for Python
    compatibleRuntimes:
      - python3.7
    allowedAccounts:
      - '*'
    retain: true
